### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by Sugarbank** [FalongShen/styletransfer#5]
Hi dude, just getting this build error...cant see the folder...whats ment to be inside it?

paperspace@psy21ytam:~/Desktop/SOFTWARE/styletransfer-master$ make -f Makefile
find: `src/caffe/layers/data': No such file or directory
find: `src/caffe/layers/data': No such file or directory
CXX src/caffe/data_transformer.cpp
In file included from include/caffe/blob.hpp:8:0,
                 from include/caffe/data_transformer.hpp:7,
                 from src/caffe/data_transformer.cpp:11:
include/caffe/common.hpp:7:18: fatal error: nccl.h: No such file or directory
 #include <nccl.h>
                  ^
compilation terminated.
make: *** [build/src/caffe/data_transformer.o] Error 1

**Comment by FalongShen** [comment]
Makefile has been fixed for some bugs. Note there are some thirdparty libs you need to install on your machine, such as "/home/shen/caffe/thirdparty/cudnn" "/home/shen/caffe/thirdparty/nccl"  "/home/shen/caffe/thirdparty/blas"  "/home/shen/caffe/thirdparty/mpich"

**Comment by Sugarbank** [comment]
have tried again..still getting an issue with there being no directory in the repo for caffe/layers/data?
Any ideas?

paperspace@psy21ytam:~/Desktop/SOFTWARE/styletransfer-master$ make -f Makefile
find: `src/caffe/layers/data': No such file or directory
find: `src/caffe/layers/data': No such file or directory
PROTOC -o src/caffe/proto/caffe.pb.cc
CXX src/caffe/data_transformer.cpp
In file included from include/caffe/blob.hpp:8:0,
                 from include/caffe/data_transformer.hpp:7,
                 from src/caffe/data_transformer.cpp:11:
include/caffe/common.hpp:7:18: fatal error: nccl.h: No such file or directory
 #include <nccl.h>
                  ^
compilation terminated.
make: *** [build/src/caffe/data_transformer.o] Error 1
paperspace@psy21ytam:~/Desktop/SOFTWARE/styletransfer-master$

**Comment by FalongShen** [comment]
The data folder has been added and I uploaded a pre-built version of the code.
